spring:
  application:
    name: test-spring-app

  datasource:
    url: jdbc:postgresql://localhost:5433/kma_bookingapp
    username: root
    password: 123456A@
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
urlClient: http://localhost:3000
