version: "3.8"

services:
  postgres:
    container_name: postgres-16
    image: postgis/postgis:16-3.4-alpine
    platform: linux/amd64
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456A@}
      POSTGRES_DB: ${POSTGRES_DB:-kma_bookingapp}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - cdattt-booking-db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  cdattt-booking-db:
